package:
  name: simstack 
  version: "1.5.1"
about:
  home: https://github.com/not_yet_existings
  license_family: proprietary
  summary: 
build:
  script: python -m pip install --no-deps --ignore-installed -vv .
  noarch: python
  number: 0
  entry_points:
    - simstack = simstack.SimStackEntryPoint:main
source:
  path: ../
requirements:
  build:
    - flit
  run:
    - python>=3.10
    - pyside6>=6.8
    - yaml >=0.2.5,<0.3.0
    - pyyaml >=6.0.0,<6.1.0
    - simstackserver >=1.5.0,<1.6.0
test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest
