package:
  name: simstack 
  version: "1.0.5"
about:
  home: https://github.com/not_yet_existings
  license: proprietary
  summary: 
build:
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
source:
  path: ../
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - meson
    - ninja
    - mesonpep517
    - python {{ python }}
    - cython =>0.29.1
  run:
    - python {{ python }}
    - pyqt >=5.15.3,<5.16
    - pyqtwebengine >=5.15.3,<5.16
    - qt.py ==1.1.0
    - yaml >=0.2.5,<0.3.0
    - pyyaml >=6.0.0,<6.1.0
    - simstackserver >=1.0.1,<1.1.0
test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest
