package:
  name: simstack 
  version: "1.2.3"
about:
  home: https://github.com/not_yet_existings
  license_family: proprietary
  summary: 
build:
  script: python -m pip install --no-deps --ignore-installed -vv .
  noarch: python
  number: 0
source:
  path: ../
requirements:
  build:
    - flit
  run:
    - python>=3.8
    - pyqt>=5.15.4,<5.16
    - pyqtwebengine >=5.15.4,<5.16
    - qt.py ==1.1.0
    - yaml >=0.2.5,<0.3.0
    - pyyaml >=6.0.0,<6.1.0
    - simstackserver >=1.2.0,<1.3.0
test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest
