package:
  name: simstack
  version: "1.6.1"
about:
  home: https://github.com/NanomatchGmbH/simstack
  license: MIT
  summary:
source:
  git_url: ../
build:
  script: "python -m pip install --no-deps --ignore-installed -vv ."
  noarch: python
requirements:
  build:
    - flit
  run:
    - python>=3.10
    - pyside6>=6.8
    - yaml >=0.2.5,<0.3.0
    - pyyaml >=6.0.0,<6.1.0
    - simstackserver >=1.6.0,<1.7.0
